- name: Install needrestart
  ansible.builtin.apt:
    name: needrestart
    update_cache: true

- name: Set needrestart mode to automatic
  ansible.builtin.include_role:
    name: perl_string_option
  args:
    path: /etc/needrestart/needrestart.conf
    name: $nrconf{restart}
    value: a
