---
- name: Systemd
  hosts: server

  tasks:
    - name: Ensure logs are persisted
      community.general.ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: Storage
        value: persistent
      notify: Restart journald

  handlers:
    - name: Restart journald
      ansible.builtin.command:
        systemctl restart systemd-journald

- name: Node.js
  hosts: server

  vars: 
    node_version: 18.17.1

  vars_files:
    - ./vars.yml

  tasks:
    - name: Ensure node user is created
      ansible.builtin.user: 
        name: node
        password: "{{ node_password | password_hash('sha512') }}"

    - name: Ensure NVM is installed
      become: true
      become_user: node
      ansible.builtin.script: ./install-nvm.sh

    - name: Ensure Node.js is installed
      become: true
      become_user: node
      ansible.builtin.shell: "source ~/.nvm/nvm.sh && nvm install {{ node_version }}"
      args:
        executable: /bin/bash

    - name: Ensure JS code is deployed
      ansible.builtin.copy:
      args:
        src: ./server.js
        dest: /home/node/server.js
        mode: u+rx-w,g-rwx,o-rwx
        owner: node

    - name: Ensure server service created
      ansible.builtin.template:
        src: ./node.service.j2
        dest: /etc/systemd/system/node.service
      register: unit_file

    - name: Start server
      ansible.builtin.systemd:
        name: node.service
        daemon_reload: true
        state: started
      when: not unit_file.changed

    - name: Restart server
      ansible.builtin.systemd:
        name: node.service
        daemon_reload: true
        state: restarted
      when: unit_file.changed

    - name: Ensure server is running
      ansible.builtin.command:
        systemctl is-active node.service
